---
title: "4.1primary analysis deciles"
author: "Tianshu Liu"
date: "2023-06-05"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#call packages and data
##package and self-create function
```{r, include=FALSE}
rm(list=ls())
#set working directory load package-----------------
working_path<-'/well/emberson/users/hma817/projects/existing_PRS'
data_path<-paste(working_path,'/data',sep='')
graphs_path<-paste(working_path,'/graphs',sep='')
setwd(working_path)

library(data.table)
library(ggplot2)
library(tidyr)
library(dplyr)
library(pROC)
library(ROCR)
library(caret)
library(corrplot)
library(DescTools)
library(flextable)
library(forestploter)
library(Epi)


```

##data
```{r,include=FALSE}
data<-readRDS(paste(data_path,"FullData_standardisedPRS_31May2023.rds",sep="/"))
data<-data[,c(1:32,35:41)]
colnames(data)[33:39]<-sub("_standardised","",colnames(data)[33:39])#remove standardised after all PRS names to make column names shorter
colnames(data)[39]<-"custom_Oni_Orisan"# change custom_Oni-Orisan to Oni_Orisan so that formula() can read it

model_table_top<-readRDS(paste(data_path,"/model_table_top.rds",sep=""))

source("/gpfs3/well/emberson/users/hma817/codes/R_TablesFunction_27Sep2022_TL.r")
source("/gpfs3/well/emberson/users/hma817/projects/existing_PRS/0.1.utils.R")  
```

#Analysis


```{r,include=FALSE}

#for (i in 1:7){
 # quintile<-ntile(data[,32+i],5)
 
 # data[,39+i]<-factor(quintile,levels=c(1:5))
 # colnames(data)[39+i]<-paste(colnames(data)[32+i],"cat",sep="_")
#}

#saveRDS(data,paste(data_path,"/analysis_data_31May2023.rds",sep=""))
#data_up<-data[,c(1:32,40:46)]
```

```{r,include=FALSE}
for (i in 1:7){
  quintile_cutoff<-quantile(data[,32+i],probs=seq(0,1,0.2),na.rm=F)
 
  data[,39+i]<-cut(data[,32+i], breaks=quintile_cutoff,labels = c(1:5),include.lowest=TRUE)
  colnames(data)[39+i]<-paste(colnames(data)[32+i],"cat",sep="_")
}
data_up<-data[,c(1:32,40:46)]

saveRDS(data,paste(data_path,"/analysis_data_31May2023.rds",sep=""))
```



## EPA

```{r,include=FALSE}

non_adjustment=NULL
partial_adjustments=c("AGE","SEX")
full_adjustments = c("AGE","SEX","WHRATIO","SBP","DBP","EDU_LEVEL","smokegp","diabetes_at_baseline")



```

```{r,include=FALSE}
model_output_simple<-create_output_table(trainsplit = F,data_up,adjustments=non_adjustment,outcome="prevalent_CHD_EPA",namew=NULL,type = "cat")

model_output_partial<-create_output_table(trainsplit = F,data_up,adjustments=partial_adjustments,outcome="prevalent_CHD_EPA",namew="partial",type = "cat")

model_output_full<-create_output_table(trainsplit = F,data_up,adjustments=full_adjustments,outcome="prevalent_CHD_EPA",namew="full",type = "cat")

```

### calculate floated absolute risk

```{r}
model_output_list<-list(model_output_partial,model_output_full)
#saveRDS(model_output_list,paste(data_path,"/prevalent_CHD_EPA_cat_logistic_06Jun2023.rds",sep=""))

#plot_FAR_up(model_output_list,name=c("Partial","Full"),outcome="Prevalent_CHD_EPA")
plot_FAR_gg(model_output_list,name=c("Partial","Full"),outcome="Prevalent_CHD_EPA",data = data)

```



```{r,include=FALSE}

model_output_partial_table<-model_output_partial[[1]]
model_output_full_table<-model_output_full[[1]]
prevalent_EPA_cat<-combine_model_tables(tables=list(model_output_partial_table,model_output_full_table),name = c("Partially adjusted","Fully adjusted"),log_cox = "log")

#saveRDS(prevalent_EPA_cat,paste(data_path,"/Prevalent_EPA_cat_AUC_table_06Jun2023.rds",sep=""))
```

```{r,echo=FALSE}
flex_cat<-my_table(prevalent_EPA_cat,y=c(1:3,7),x=1:8)
flex_cat<-footnote(flex_cat,i=c(3,7),j=1,part="body",value = as_paragraph(c("Partially adjusted models adjust for Sex and baseline age. Fully adjusted models additionally adjust for waist-to-hip ratio, systolic and diastolic blood pressure, education attainmen level, smoking status,diabetes at baseline")),ref_symbols = c("*"))
flex_cat <- add_header_row(flex_cat, values =  c(" ", "European PRS","Non-European PRS"),
    colwidths = c(1, 4,3), top = T)

flex_cat <- compose(flex_cat, i = c(5,9), j = 1, part = "body",
    value = as_paragraph(
      "\U{00A0}\U{00A0}Naglekerke pseudo R",
      as_sup("2")   ) )

flex_cat <- compose(flex_cat, i = c(6,10), j = 1, part = "body",
    value = as_paragraph(
      "\U{00A0}\U{00A0}Lee's pseudo R",
      as_sup("2")   ) )


my_theme(flex_cat,y=c(1,2,6),set_padding = 3,fontsize = 8,header_border = 7)

```




## EPO

```{r,include=FALSE}
model_output_simple<-create_output_table(trainsplit = F,data_up,adjustments=non_adjustment,outcome="prevalent_CHD_EPO",namew=NULL,type = "cat")

model_output_partial<-create_output_table(trainsplit = F,data_up,adjustments=partial_adjustments,outcome="prevalent_CHD_EPO",namew="partial",type = "cat")

model_output_full<-create_output_table(trainsplit = F,data_up,adjustments=full_adjustments,outcome="prevalent_CHD_EPO",namew="full",type = "cat")
```


### calculate floated absolute risk

```{r,include=FALSE}
model_output_list<-list(model_output_partial,model_output_full)
saveRDS(model_output_list,paste(data_path,"/prevalent_CHD_EPO_cat_logistic_06Jun2023.rds",sep=""))
#plot_FAR_up(model_output_list,name=c("Partial","Full"),outcome="Prevalent_CHD_EPO",data=data)
plot_FAR_gg(model_output_list,name=c("Partial","Full"),outcome="Prevalent_CHD_EPO",data=data)

```

```{r,include=FALSE}
model_output_partial_table<-model_output_partial[[1]]
model_output_full_table<-model_output_full[[1]]
prevalent_EPO_cat<-combine_model_tables(tables=list(model_output_partial_table,model_output_full_table),name = c("Partially adjusted","Fully adjusted"),log_cox = "log")
saveRDS(prevalent_EPO_cat,paste(data_path,"/Prevalent_EPO_cat_AUC_table_06Jun2023.rds",sep=""))
```

```{r,echo=FALSE}
flex_cat<-my_table(prevalent_EPO_cat,y=c(1:3,7),x=1:8)
flex_cat<-footnote(flex_cat,i=c(3,7),j=1,part="body",value = as_paragraph(c("Partially adjusted models adjust for Sex and baseline age. Fully adjusted models additionally adjust for waist-to-hip ratio, systolic and diastolic blood pressure, education attainmen level, smoking status,diabetes at baseline")),ref_symbols = c("*"))
flex_caat <- add_header_row(flex_cat, values =  c(" ", "European PRS","Non-European PRS"),
    colwidths = c(1, 4,3), top = T)

flex_cat <- compose(flex_cat, i = c(5,9), j = 1, part = "body",
    value = as_paragraph(
      "\U{00A0}\U{00A0}Naglekerke pseudo R",
      as_sup("2")   ) )

flex_cat <- compose(flex_cat, i = c(6,10), j = 1, part = "body",
    value = as_paragraph(
      "\U{00A0}\U{00A0}Lee's pseudo R",
      as_sup("2")   ) )


my_theme(flex_cat,y=c(1,2,6),set_padding = 3,fontsize = 8,header_border = 7)
```

