---
title: "5.1 Secondary Analysis (CAD mortality)"
author: "Tianshu Liu"
date: "2023-05-11"
output: word_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

#call packages and data
##package and self-create function
```{r, include=FALSE}
rm(list=ls())
#set working directory load package-----------------
working_path<-'/well/emberson/users/hma817/projects/existing_PRS'
data_path<-paste(working_path,'/data',sep='')
graphs_path<-paste(working_path,'/graphs',sep='')
setwd(working_path)

library(data.table)
library(ggplot2)
library(ggfortify)
library(tidyr)
library(dplyr)
library(pROC)
library(ROCR)
library(caret)
library(corrplot)
library(DescTools)
library(flextable)
library(survival)
library(survminer)
library(dynpred)
library(Epi)

```

##data
```{r,include=FALSE}
data<-readRDS(paste(data_path,"FullData_timesplit_31May2023.rds",sep="/"))
data2<-readRDS(paste(data_path,"FullData_standardisedPRS_mortality_31May2023.rds",sep="/"))

variants_included<-readRDS(paste(data_path,"variants_included.rds",sep="/"))
  variant_t<-data.frame(t(variants_included))
  colnames(variant_t)<-variant_t[1,]
  variant_t<-variant_t[2,]
  variant_t<-cbind(rownames(variant_t),variant_t)
  colnames(variant_t)[1]<-NA
  colnames(variant_t)[8]<-"custom_Oni_Orisan"
  variant_t[1,1]<-"Number of SNPs"
variant_t[2:8]<-prettyNum(variant_t[2:8], big.mark = ",", scientific = FALSE)
 PCs<-c(paste0("PC",1:7)) 
 data$agegroup<-factor(data$agegroup,levels = c(1:5))
 source("/gpfs3/well/emberson/users/hma817/codes/R_TablesFunction_27Sep2022_TL.r")
source("/gpfs3/well/emberson/users/hma817/projects/existing_PRS/0.2.utils_cox.R")
```





```{r,echo=FALSE}
#check km plot of normal data and lexis expansion data
autoplot(survfit(Surv(time=time_in,time2 = time_out,EPO001_up_75)~1,data=data),data=data,risk.table = T)
autoplot(survfit(Surv(followup,data2$EPO001_up&data2$AGE_followup<75)~1,data=data2),data=data2,risk.table = T)
```






```{r,echo=FALSE}
#check events in two data are matched up
table(data$EPA001_up_75)
table(data$EPO001_up_75)
table(data2$EPA001_up&data2$AGE_followup<75)
table(data2$EPO001_up&data2$AGE_followup<75)
```
```{r,echo=FALSE}
#check outputs of two datasets are the same if don't account for time-dependent variables
fit<-coxph(Surv(time_in,time_out,EPO001_up_75,type = "counting")~SEX,data=data)
summary(fit)


fit2<-coxph(Surv(followup,data2$EPO001_up&data2$AGE_followup<75)~SEX,data=data2)
summary(fit2)
```


```{r,include=FALSE}
#mort_fit1<-survfit(Surv(time_in,time_out,EPO001_up_75)~diabetes_at_baseline, data)
#mort_fit2<-survfit(Surv(time_in,time_out,EPO001_up_75)~SEX, data)
#mort_fit3<-survfit(Surv(time_in,time_out,EPO001_up_75)~EDU_LEVEL, data)
#mort_fit4<-survfit(Surv(time_in,time_out,EPO001_up_75)~smokegp,data)


```
```{r,echo=FALSE}

#ggsurvplot(mort_fit1, data = final_data,risk.table = T,pval = T)
#ggsurvplot(mort_fit2, data = final_data,risk.table = T,pval = T)
#ggsurvplot(mort_fit3, data = final_data,risk.table = T,pval = T)
#ggsurvplot(mort_fit4, data = final_data,risk.table = T,pval = T)

#covariate<-c("Baseline diabetes","Gender","Education level","Smoking status")
#fit_list<-list(mort_fit1,mort_fit2,mort_fit3,mort_fit4)
#for (i in 1:4){
  
#  p<-ggsurvplot(fit_list[[i]], data = data,risk.table = T)
  #jpeg(paste(graphs_path,"/KM_plot_",covariate[i],".jpg",sep=""),width = 1000,height = 800)
#  print(p)
  
 #dev.off()
#}
```

##premature deaths------

#adjust for age-bands

```{r,echo=FALSE}
model_no_prs<-coxph(Surv(time_in,time_out,EPO001_up_75,type = "counting")~SEX+as.factor(agegroup)+EDU_LEVEL+as.factor(diabetes_at_baseline)+smokegp+ SBP + 
    DBP + WHRATIO,data=data)

```


```{r,echo=FALSE}
#summary(model_no_prs)
cox.zph(model_no_prs)

round(ci_manual(x=concordance(model_no_prs)$concordance,se=sqrt(concordance(model_no_prs)$var)),3)
```


### CAD mortality as EPA001
```{r,include=FALSE}
#plot km plot for catgorical prs
#start_column=which( colnames(final_data)%in%paste(colnames(variant_t),"_cat",sep=""))
#for (i in 1:7){
  
#  p<-ggsurvplot(survfit(create_surv_formula(model_type="simple",data=final_data,full_adjustments,outcome="EPA001_up",pgs_name=colnames(final_data)[start_column[i]]), data = final_data),pval = T,risk.table = T)
#  jpeg(paste(graphs_path,"/KM_plot_",colnames(final_data)[start_column[i]],".jpg",sep=""),width = 1000,height = 800)
#  print(p)
  
#  dev.off()
#}
```


```{r,include=FALSE}
numeric_variable<-c("SBP","DBP","WHRATIO")

for(i in 1:length(numeric_variable)){
  plot_martingale(numeric_variable[i],outcome="EPO001_up_75")
}

for (i in 1:7){
 plot_martingale(colnames(variant_t)[i+1],outcome="EPO001_up_75",include = "linear",save=paste("/cox/",colnames(variant_t)[i+1],sep=""))
}
```



```{r,include=FALSE}
outcome="EPA001_up_75"
partial_adjustments=c("SEX","agegroup")
full_adjustments = c(partial_adjustments,c("WHRATIO","SBP","DBP","EDU_LEVEL","smokegp","diabetes_at_baseline"))
```

```{r,include=FALSE}
model_output_simple<-create_output_table_cox(data=data,adjustments=partial_adjustments,outcome=outcome,trainsplit = F)
```

```{r,include=FALSE}
model_output_full<-create_output_table_cox(data=data,adjustments=full_adjustments,outcome=outcome,trainsplit = F,namew = "_full")
```

```{r,include=FALSE}

model_output_partial_t<-model_to_table_cox(model_output_simple)
  model_output_full_t<-model_to_table_cox(model_output_full)
 EPO001_cont<-rbind(variant_t,
                        c("Partially adjusted Model", rep(NA,7)),
                        model_output_partial_t,
                        
                        c("Fully Adjusted Model", rep(NA,7)),
                        model_output_full_t
  )
 rownames(EPO001_cont)<-seq(1:nrow(EPO001_cont))
  colnames(EPO001_cont)[1]<-"95% CI"
  EPO001_cont$`95% CI`[c(3,4,6,7)]<-paste("\U{00A0}\U{00A0}",EPO001_cont$`95% CI`[c(3,4,6,7)],sep="")
  #saveRDS(EPO001_cont,paste(data_path,"/EPO001_cont_model_outcomes_31May2023.rds",sep=""))
```

### HR table

```{r,echo=TRUE}
flex_cont<-my_table(EPO001_cont,y=c(1,2,5),x=1:8)
flex_cont<-footnote(flex_cont,i=c(2,5),j=1,part="body",value = as_paragraph(c("Partial adjusted models adjust for Sex and age groups. Fully adjusted models additionally adjust for  waist-to-hip ratio, systolic and diastolic blood pressure, education attainmen level, smoking status,diabetes at baseline")),ref_symbols = c("*"))
flex_cont <- add_header_row(flex_cont, values =  c(" ", "Polygenic risk scores"),
    colwidths = c(1, 7), top = T)



my_theme(flex_cont,y=c(1,4,7),set_padding = 3,fontsize = 12)
```

##plot forest plot
```{r,include=FALSE}
model_output_full_up<-model_output_full
colnames(model_output_full_up)[1:9]<-paste(colnames(model_output_full)[1:9],"_full",sep="")
model_output<-merge(model_output_simple,model_output_full_up,by="row.names")
rownames(model_output)<-model_output$Row.names
model_output<-model_output[,2:ncol(model_output)]
model_output$pgsname<-rownames(model_output)

model_output[,c(1:8,10:17)]<-apply(model_output[,c(1:8,10:17)],2,as.numeric)
#model_output$'HR (95%CI)'<-paste(model_output$HR," (",model_output$LR,"-",model_output$UR,")")
model_output$" "<- paste(rep(" ", 40), collapse = " ")
forest_table<-model_output[,c("pgsname"," ","HR","LR","UR","pval","HR_full","LR_full","UR_full","pval_full","case_no","control_no","case_no_full","control_no_full")]
forest_table<-forest_table[c(3:7,2:1),]



```





```{r,include=FALSE}
forest_table$"HR per SD (95%CI)"<-paste(forest_table$HR,"(",forest_table$LR,"-",forest_table$UR,")",sep="")
forest_table$"HR per SD (95%CI) "<-paste(forest_table$HR_full,"(",forest_table$LR_full,"-",forest_table$UR_full,")",sep="")
colnames(forest_table)[c(1,6,10,11:14)]<-c("                                   ","p-value","p-value ","CAD cases","No CAD","CAD cases ","No CAD ")
```

#### type 1

```{r,include=FALSE}
p <- forest(forest_table[,c(1,11,12,15,13,14,16,2)],
            est = list(forest_table$HR,forest_table$HR_full),
            lower = list(forest_table$LR,forest_table$LR_full), 
            upper = list(forest_table$UR,forest_table$UR_full),
            ci_column = 8,
            ref_line = 1,
            arrow_lab = c("Lower risk of CAD", "Higher risk of CAD"),
            xlim = c(0.9, 1.35),
            ticks_at = c(0.9, 1, 1.1,1.2,1.3),
            footnote = "\n\n\n\n\n\n\n\n\n Partially adjusted model adjusts for sex and age group. Fully adjusted model additionally adjusts for education level, smoking status, blood pressure and waist-hip ratio ",
            theme=tm2)


p <- insert_text(p, text = "Simple model",
              part = "header",
              col = 2:4,
              gp = gpar(fontface = "bold",fontsize=6))
p <- add_text(p, text = "Full model",
              part = "header",
              col = 5:7,
              row=1,
              gp = gpar(fontface = "bold",fontsize=6))
p <- add_border(p, 
                part = "header", 
                row = 2,
                col = 1:8, gp = gpar(lwd = 1))
p <- add_border(p, 
                part = "header", 
                row = 1,
                col = 2:4,
                gp = gpar(lwd = .5))
p <- add_border(p, 
                part = "header", 
                row = 1,
                col = 5:7,
                gp = gpar(lwd = .5))

p <- add_border(p, 
                part = "body", 
                col = 2:7,row=1:6,
                gp = gpar(lwd = .5))
p <- add_border(p, 
                part = "body", 
                row = 1:7,col=4,
                gp = gpar(lwd = .5),where="right")



p<- edit_plot(p, row = 1:7, col=1,
               gp = gpar(fontface = "bold"))

a<-get_wh(p,unit = "cm")

png(paste(graphs_path,"/cox/Cox_forestplot1_",outcome,".png",sep=""), res = 150, width = a[1], height = a[2], units = "cm")
print(p)
dev.off()
```
#### type2

```{r,include=FALSE}
  hr_ci<-NA
forest_table<-data.frame(subgroup=NA,case_no=NA,control_no=NA,OR=NA,LR=NA,UR=NA,hr_ci=NA,pval=NA)
model_list<-list(model_output_simple,model_output_full)
    name<-c("\U{00A0}\U{00A0}Partially adjusted","\U{00A0}\U{00A0}Fully adjusted")
    for (i in 1:7){
      forest_table<-rbind(forest_table,c(rownames(model_output_simple)[i],rep(" ",7)))
      for (j in 1:2){
        hr_ci<-paste(round(as.numeric(model_list[[j]][i,1]),3),"(",model_list[[j]][i,2],"-",model_list[[j]][i,3],")",sep="")
        row_input<-unlist(c(name[j],model_list[[j]][i,c("case_no","control_no","HR","LR","UR")],
                            hr_ci,model_list[[j]][i,c("pval")]))
        forest_table<-rbind(forest_table,row_input,make.row.names=F)
      }
      
    }
    forest_table<-forest_table[2:nrow(forest_table),]
```



```{r,include=FALSE}
forest_table$" "<- paste(rep(" ", 40), collapse = " ")
colnames(forest_table)<-c("  ","CAD case", "No CAD", "HR","LR","UR","HR (95%CI)","p-value","   ")

p <- forest(forest_table[,c(1:3,7,9,8)],
            est = as.numeric(forest_table$HR),
            lower = as.numeric(forest_table$LR), 
            upper = as.numeric(forest_table$UR),
            ci_column = 5,
            ref_line = 1,
            arrow_lab = c("Lower risk of CAD", "Higher risk of CAD"),
            xlim = c(0.9, 1.35),
            ticks_at = c(0.9, 1, 1.1,1.2,1.3),
            footnote = "\n\n\n\n\n\n\n\n\n Partially adjusted model adjusts for sex and age group. Fully adjusted model additionally adjusts for education level, smoking status, \n blood pressure and waist-hip ratio ",
            theme=tm2)

```

```{r,include=FALSE}

p <- add_border(p, 
                part = "header", 
                row = 1,
                col = 1:6, gp = gpar(lwd = 1))

p <- add_border(p, 
                part = "body", 
                col = 2:4,row=1:20,
                gp = gpar(lwd = .5))



p<- edit_plot(p, row = c(seq(1,21,by=3)), col=1,
               gp = gpar(fontface = "bold"))

a<-get_wh(p,unit = "cm")

png(paste(graphs_path,"/cox/Cox_forestplot2_",outcome,".png",sep=""), res = 200, width = a[1], height = a[2], units = "cm")
print(p)
dev.off()
```

