---
title: "5.2 CAD mortality by decile"
author: "Tianshu Liu"
date: "2023-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#call packages and data
##package and self-create function
```{r, include=FALSE}
rm(list=ls())
#set working directory load package-----------------
working_path<-'/well/emberson/users/hma817/projects/existing_PRS'
data_path<-paste(working_path,'/data',sep='')
graphs_path<-paste(working_path,'/graphs',sep='')
setwd(working_path)

library(data.table)
library(ggplot2)
library(ggfortify)
library(tidyr)
library(dplyr)
library(pROC)
library(ROCR)
library(caret)
library(corrplot)
library(DescTools)
library(flextable)
library(survival)
library(survminer)
library(dynpred)
library(Epi)
library(forestploter)

```

##data
```{r,include=FALSE}
data<-readRDS(paste(data_path,"FullData_timesplit_31May2023.rds",sep="/"))
data2<-readRDS(paste(data_path,"FullData_standardisedPRS_mortality_31May2023.rds",sep="/"))


model_table_top<-readRDS(paste(data_path,"/model_table_top.rds",sep=""))
 data$agegroup<-factor(data$agegroup,levels = c(1:5))
 source("/gpfs3/well/emberson/users/hma817/codes/R_TablesFunction_27Sep2022_TL.r")
source("/gpfs3/well/emberson/users/hma817/projects/existing_PRS/0.1.utils.R")
```

```{r}
model_simple<-coxph(Surv(time_in,time_out,EPO001_up_75,type = "counting")~PGS000011_cat+SEX,data=data)

fl_a<-float(model_simple,factor="PGS000011_cat")
```

### EPO 

```{r,include=FALSE}
data_up<-data[,c(1:32,40:57)]
outcome="EPO001_up_75"
non_adjustment=NULL
partial_adjustments=c("SEX")
strata="agegroup"
full_adjustments = c(partial_adjustments,c("WHRATIO","SBP","DBP","EDU_LEVEL","smokegp","diabetes_at_baseline"))
```

```{r,include=FALSE}
model_output_simple<-create_output_table_cox(trainsplit = F,data_up,adjustments=non_adjustment,outcome=outcome,namew=NULL,type = "cat")

model_output_partial<-create_output_table_cox(trainsplit = F,data_up,adjustments=partial_adjustments,outcome=outcome,namew="partial",type = "cat",strata = strata)

model_output_full<-create_output_table_cox(trainsplit = F,data_up,adjustments=full_adjustments,outcome=outcome,namew="full",type = "cat",strata = strata)
```

```{r,include=FALSE}
model_output_list<-list(model_output_partial,model_output_full)
saveRDS(model_output_list,paste(data_path,"/EPO001_cat_cox_07Jun2023.rds",sep=""))
plot_FAR_gg(model_output_list,name=c("Partial","Full"),outcome="EPO001",type="HR",data = data)
```

```{r,include=FALSE}
model_output_partial_table<-model_output_partial[[1]]
model_output_full_table<-model_output_full[[1]]
EPO_cat<-combine_model_tables(tables=list(model_output_partial_table,model_output_full_table),name = c("Partially adjusted","Fully adjusted"),log_cox = "cox")
saveRDS(EPO_cat,paste(data_path,"/EPO001_cat_AUC_table_06Jun2023.rds",sep=""))
```

```{r,echo=FALSE}
flex_cat<-my_table(EPO_cat,y=c(1:3,5),x=1:8)
flex_cat<-footnote(flex_cat,i=c(3,5),j=1,part="body",value = as_paragraph(c("Partially adjusted models adjust for Sex and baseline age. Fully adjusted models additionally adjust for waist-to-hip ratio, systolic and diastolic blood pressure, education attainmen level, smoking status,diabetes at baseline")),ref_symbols = c("*"))
flex_cat <- add_header_row(flex_cat, values =  c(" ", "European PRS","Non-European PRS"),
    colwidths = c(1, 4,3), top = T)


my_theme(flex_cat,y=c(1,2,4),set_padding = 3,fontsize = 8,header_border = 7)
```

### EPA
```{r,include=FALSE}
outcome="EPA001_up_75"
non_adjustment=NULL
partial_adjustments=c("SEX")
strata="agegroup"
full_adjustments = c(partial_adjustments,c("WHRATIO","SBP","DBP","EDU_LEVEL","smokegp","diabetes_at_baseline"))
```

```{r,include=FALSE}
model_output_simple<-create_output_table_cox(trainsplit = F,data_up,adjustments=non_adjustment,outcome=outcome,namew=NULL,type = "cat")

model_output_partial<-create_output_table_cox(trainsplit = F,data_up,adjustments=partial_adjustments,outcome=outcome,namew="partial",type = "cat",strata=strata)

model_output_full<-create_output_table_cox(trainsplit = F,data_up,adjustments=full_adjustments,outcome=outcome,namew="full",type = "cat",strata=strata)
```

```{r,include=FALSE}
model_output_list<-list(model_output_partial,model_output_full)
#saveRDS(model_output_list,paste(data_path,"/EPA001_cat_cox_07Jun2023.rds",sep=""))
plot_FAR_gg(model_output_list,name=c("Partial","Full"),outcome="EPA001",type="HR",data=data)
```

```{r,include=FALSE}
model_output_partial_table<-model_output_partial[[1]]
model_output_full_table<-model_output_full[[1]]
EPA_cat<-combine_model_tables(tables=list(model_output_partial_table,model_output_full_table),name = c("Partially adjusted","Fully adjusted"),log_cox = "cox")
saveRDS(EPA_cat,paste(data_path,"/EPA001_cat_AUC_table_06Jun2023.rds",sep=""))
```

```{r}
flex_cat<-my_table(EPA_cat,y=c(1:3,5),x=1:8)
flex_cat<-footnote(flex_cat,i=c(3,5),j=1,part="body",value = as_paragraph(c("Partially adjusted models adjust for Sex and baseline age. Fully adjusted models additionally adjust for waist-to-hip ratio, systolic and diastolic blood pressure, education attainmen level, smoking status,diabetes at baseline")),ref_symbols = c("*"))
flex_cat <- add_header_row(flex_cat, values =  c(" ", "European PRS","Non-European PRS"),
    colwidths = c(1, 4,3), top = T)


my_theme(flex_cat,y=c(1,3),set_padding = 3,fontsize = 8,header_border = 7)
```

